apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: default
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/myapp/app.log
      pos_file /var/log/fluentd-myapp.pos
      tag myapp.logs
      format none
    </source>

    <match myapp.logs>
      @type elasticsearch
      host elasticsearch.logging.svc.cluster.local
      port 9200
      logstash_format true
      logstash_prefix myapp
      flush_interval 5s
    </match>
